Implementing the refactoring
miatrinity/routeines pull request #19
Opened 2020-04-17 08:24 UTC by miatrinity

2020-04-17 08:33 UTC, MiaSinek requested changes

2020-04-17 08:33 UTC, MiaSinek commented on app/presenters/base_presenter.rb
> +  # presents :routine_flow
Remove comment

2020-04-17 08:33 UTC, MiaSinek commented on app/presenters/base_presenter.rb
> +  end
Is this needed at all? 🤔

2020-04-17 08:33 UTC, MiaSinek commented on app/presenters/routine_flow_presenter.rb
> +    routine_flow.title
Delegate to routine_flow

2020-04-17 08:33 UTC, MiaSinek commented on app/presenters/routine_flow_presenter.rb
> +            class: 'button is-large is-info is-fullwidth'
Are these presenting routine_flow? Where should we move so it semantically makes more sense? 🤔

2020-04-17 08:34 UTC, miatrinity commented on app/presenters/base_presenter.rb
> +  # presents :routine_flow
Okay!

2020-04-17 08:38 UTC, MiaSinek commented on app/presenters/base_presenter.rb
> +  end
Nope! 💪

2020-04-17 08:38 UTC, miatrinity commented on app/presenters/base_presenter.rb
> +  end
Nope! 💪

2020-04-17 08:41 UTC, miatrinity commented on app/presenters/routine_flow_presenter.rb
> +    routine_flow.title
Done

2020-04-18 09:17 UTC, MiaSinek approved these changes

2020-04-18 09:18 UTC, merged