Feature/execute routine
miatrinity/routeines pull request #6
Opened 2020-03-27 08:11 UTC by miatrinity

2020-03-28 09:05 UTC, MiaSinek requested changes
Address the comments & refactor tests!

2020-03-28 09:05 UTC, MiaSinek commented on app/controllers/routine_flows_controller.rb
> +  end
Move `redirect_to` to `start_routine_flow` to be more consistent with the `update` and `destroy` method logic

2020-03-28 09:05 UTC, MiaSinek commented on app/models/concerns/chainable.rb
> +  end
Move to the bottom of the module - to be after `update_last_step_before_deletion` , which calls it -  for enhanced readibility

2020-03-28 09:05 UTC, MiaSinek commented on app/models/flow_step.rb
> +  enum status: { inactive: 0, active: 1, complete: 2 }
Change status from `inactive` to `upcoming` - semantically more meaningful and less confusing status when running the routine flow

2020-03-28 09:05 UTC, MiaSinek commented on app/models/routine.rb
Right now, `routine` can not be deleted because of foreign key constraints. Investigate!

2020-03-28 09:05 UTC, MiaSinek commented on app/models/routine_flow.rb
> +  def take_next_step!
Rename this to `take_next_flow_step!`

2020-03-28 09:05 UTC, MiaSinek commented on app/models/routine_flow.rb
> +    end
Wrap this into `FlowStep.transaction` to make sure there is one transaction, rather than one for every step.

2020-03-28 09:05 UTC, MiaSinek commented on app/models/routine_flow.rb
> +    flow_steps.inactive.first
Change `inactive` to `upcoming` in order to clarify the intent

2020-03-28 09:05 UTC, MiaSinek commented on app/views/flow_steps/_flow_step.html.erb
> +  <article class="media" style="align-items: center;">
Remove `style`, move it to stylesheet

2020-03-28 09:05 UTC, MiaSinek commented on app/views/flow_steps/_flow_step.html.erb
> +        <div class="level-left" style="align-items: baseline;">
Remove `style`, move it to stylesheet

2020-03-28 09:05 UTC, MiaSinek commented on app/views/routine_flows/show.html.erb
> +<section class="section">
Currently, `complete_routine_flow` does not complete the last step - fix this!

Also, the UI should be aware that the `routine_flow` has been finished, and display a trophy / do NOT display Finish/Cancel etc buttons.

2020-03-28 09:05 UTC, MiaSinek commented on app/views/routine_flows/show.html.erb
> +            <strong><%= @routine_flow.flow_steps.inactive.size + 1 %> </strong> flow <%= "step".pluralize(@routine_flow.flow_steps.inactive.size + 1) %> remaining!
Refactor this! Set up a presenter / object view or something

2020-03-28 09:05 UTC, MiaSinek commented on app/views/routine_flows/show.html.erb
> +        <div class="buttons">
Delete these

2020-03-28 09:05 UTC, MiaSinek commented on app/views/routine_flows/show.html.erb
> +          <span id="current-flow-step-title"><%= @routine_flow.flow_steps.active.first.title %></span>
Move this to presenter

2020-03-28 09:05 UTC, MiaSinek commented on app/views/routine_flows/show.html.erb
> +            <strong><%= @routine_flow.flow_steps.inactive.size + 1 %> </strong> flow <%= "step".pluralize(@routine_flow.flow_steps.inactive.size + 1) %> remaining!
Add visual space between "X flow steps remaining"

2020-03-28 09:05 UTC, MiaSinek commented on app/views/routine_flows/show.html.erb
> +          <% end %>
Move this to presenter

2020-03-28 09:05 UTC, MiaSinek commented on app/views/routine_flows/show.html.erb
> +      <%# display step with staus = inactive %>
Remove

2020-03-28 09:05 UTC, MiaSinek commented on app/views/routine_flows/show.html.erb
> +        <%= render @routine_flow.flow_steps.inactive %>
inactive -> upcoming

2020-03-28 09:05 UTC, MiaSinek commented on app/views/routine_flows/show.html.erb
> +        <!-- <a class="button is-success " href="new-identity.html">Start</a> -->
Remove

2020-03-28 09:05 UTC, MiaSinek commented on app/views/routine_flows/show.html.erb
> +        <a class="button is-medium is-danger is-fullwidth" href="new-identity.html">I want to quit! Get me out of here!</a>
Implement or remove this (not necessary for MVP?)

2020-03-28 09:05 UTC, MiaSinek commented on app/views/routines/_routine.html.erb
> +    </div>
Fix design

2020-03-28 09:05 UTC, MiaSinek commented on config/routes.rb
> +  get :index, controller: "routine_flow_report"
What is this? Remove?

2020-03-28 09:08 UTC, miatrinity commented on app/controllers/routine_flows_controller.rb
> +  end
Done!

2020-03-28 09:12 UTC, miatrinity commented on app/models/concerns/chainable.rb
> +  end
Done!

2020-03-28 09:19 UTC, miatrinity commented on app/models/flow_step.rb
> +  enum status: { inactive: 0, active: 1, complete: 2 }
Done

2020-03-28 14:48 UTC, miatrinity commented on app/models/routine.rb
Done!

2020-03-28 14:51 UTC, miatrinity commented on app/models/routine_flow.rb
> +  def take_next_step!
Done!

2020-03-28 15:00 UTC, miatrinity commented on app/models/routine_flow.rb
> +    end
Done!

2020-03-28 15:01 UTC, miatrinity commented on app/models/routine_flow.rb
> +    flow_steps.inactive.first
Done

2020-03-28 15:05 UTC, miatrinity commented on app/views/routine_flows/show.html.erb
> +        <div class="buttons">
Done!

2020-03-28 15:10 UTC, miatrinity commented on app/views/routine_flows/show.html.erb
> +            <strong><%= @routine_flow.flow_steps.inactive.size + 1 %> </strong> flow <%= "step".pluralize(@routine_flow.flow_steps.inactive.size + 1) %> remaining!
Done!

2020-03-28 15:10 UTC, miatrinity commented on app/views/routine_flows/show.html.erb
> +      <%# display step with staus = inactive %>
Done!

2020-03-28 15:10 UTC, miatrinity commented on app/views/routine_flows/show.html.erb
> +        <%= render @routine_flow.flow_steps.inactive %>
Done!

2020-03-28 15:11 UTC, miatrinity commented on app/views/routine_flows/show.html.erb
> +        <!-- <a class="button is-success " href="new-identity.html">Start</a> -->
Done!

2020-03-28 15:12 UTC, miatrinity commented on app/views/routine_flows/show.html.erb
> +        <a class="button is-medium is-danger is-fullwidth" href="new-identity.html">I want to quit! Get me out of here!</a>
Let's move this functionality to next version. MVP is doing fine without it ;)

2020-03-28 15:15 UTC, miatrinity commented on config/routes.rb
> +  get :index, controller: "routine_flow_report"
Done!

2020-03-29 11:03 UTC, miatrinity commented on app/views/flow_steps/_flow_step.html.erb
> +  <article class="media" style="align-items: center;">
Done!

2020-03-29 11:05 UTC, miatrinity commented on app/views/flow_steps/_flow_step.html.erb
> +        <div class="level-left" style="align-items: baseline;">
Done

2020-03-29 11:10 UTC, miatrinity commented on app/views/routines/_routine.html.erb
> +    </div>
Done!

2020-03-29 11:39 UTC, miatrinity commented on app/views/routine_flows/show.html.erb
> +            <strong><%= @routine_flow.flow_steps.inactive.size + 1 %> </strong> flow <%= "step".pluralize(@routine_flow.flow_steps.inactive.size + 1) %> remaining!
Done!

2020-03-29 12:26 UTC, miatrinity commented on app/views/routine_flows/show.html.erb
> +          <span id="current-flow-step-title"><%= @routine_flow.flow_steps.active.first.title %></span>
Done

2020-03-29 12:26 UTC, miatrinity commented on app/views/routine_flows/show.html.erb
> +          <% end %>
Done

2020-03-29 19:37 UTC, miatrinity commented on app/views/routine_flows/show.html.erb
> +<section class="section">
D.O.N.E.

2020-03-29 19:38 UTC, merged